### ISSUE TITLE
'Why did you do this', section

### ISSUE THREAD

**Issue by Txellenne** [urthbound/sild#2]
Hi, I found this work so interesting. Thanks for sharing. Just wanted to say I spotted a mistake in the `.md` script, (I think line 26 at) the link to the posts site in the `Why did you do this` section leads to a `404 github` page.  I (guess) it should be `http://blog.jfo.click/` (including the `http://` bit).

**Comment by jfo** [comment]
Thanks for catching that, fixed.

Glad you liked it!! 😄
